// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/class.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "go.appointy.com/jaal/schema"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClassType int32

const (
	ClassType_INVALID ClassType = 0
	ClassType_REGULAR ClassType = 1
	ClassType_SERIES  ClassType = 2
)

var ClassType_name = map[int32]string{
	0: "INVALID",
	1: "REGULAR",
	2: "SERIES",
}

var ClassType_value = map[string]int32{
	"INVALID": 0,
	"REGULAR": 1,
	"SERIES":  2,
}

func (x ClassType) String() string {
	return proto.EnumName(ClassType_name, int32(x))
}

func (ClassType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5954d2856b46339d, []int{0}
}

type Class struct {
	Id          string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Area        float32            `protobuf:"fixed32,2,opt,name=area,proto3" json:"area,omitempty"`
	Strength    int32              `protobuf:"varint,3,opt,name=strength,proto3" json:"strength,omitempty"`
	IsDeleted   bool               `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Type        ClassType          `protobuf:"varint,5,opt,name=type,proto3,enum=appointy.class.v1.ClassType" json:"type,omitempty"`
	Instructors []*ServiceProvider `protobuf:"bytes,6,rep,name=instructors,proto3" json:"instructors,omitempty"`
	// Types that are valid to be assigned to Charge:
	//	*Class_PerInstance
	//	*Class_Lumpsum
	Charge               isClass_Charge       `protobuf_oneof:"charge"`
	Metadata             map[string]*Value    `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Parent               string               `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_5954d2856b46339d, []int{0}
}

func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (m *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(m, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Class) GetArea() float32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Class) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *Class) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Class) GetType() ClassType {
	if m != nil {
		return m.Type
	}
	return ClassType_INVALID
}

func (m *Class) GetInstructors() []*ServiceProvider {
	if m != nil {
		return m.Instructors
	}
	return nil
}

type isClass_Charge interface {
	isClass_Charge()
}

type Class_PerInstance struct {
	PerInstance string `protobuf:"bytes,7,opt,name=per_instance,json=perInstance,proto3,oneof"`
}

type Class_Lumpsum struct {
	Lumpsum int32 `protobuf:"varint,8,opt,name=lumpsum,proto3,oneof"`
}

func (*Class_PerInstance) isClass_Charge() {}

func (*Class_Lumpsum) isClass_Charge() {}

func (m *Class) GetCharge() isClass_Charge {
	if m != nil {
		return m.Charge
	}
	return nil
}

func (m *Class) GetPerInstance() string {
	if x, ok := m.GetCharge().(*Class_PerInstance); ok {
		return x.PerInstance
	}
	return ""
}

func (m *Class) GetLumpsum() int32 {
	if x, ok := m.GetCharge().(*Class_Lumpsum); ok {
		return x.Lumpsum
	}
	return 0
}

func (m *Class) GetMetadata() map[string]*Value {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Class) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Class) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Class) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Class) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Class_PerInstance)(nil),
		(*Class_Lumpsum)(nil),
	}
}

type Value struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Game                 string   `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_5954d2856b46339d, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Value) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

type CreateClassReq struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Class                *Class   `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClassReq) Reset()         { *m = CreateClassReq{} }
func (m *CreateClassReq) String() string { return proto.CompactTextString(m) }
func (*CreateClassReq) ProtoMessage()    {}
func (*CreateClassReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5954d2856b46339d, []int{2}
}

func (m *CreateClassReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClassReq.Unmarshal(m, b)
}
func (m *CreateClassReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClassReq.Marshal(b, m, deterministic)
}
func (m *CreateClassReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClassReq.Merge(m, src)
}
func (m *CreateClassReq) XXX_Size() int {
	return xxx_messageInfo_CreateClassReq.Size(m)
}
func (m *CreateClassReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClassReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClassReq proto.InternalMessageInfo

func (m *CreateClassReq) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateClassReq) GetClass() *Class {
	if m != nil {
		return m.Class
	}
	return nil
}

type GetClassReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClassReq) Reset()         { *m = GetClassReq{} }
func (m *GetClassReq) String() string { return proto.CompactTextString(m) }
func (*GetClassReq) ProtoMessage()    {}
func (*GetClassReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5954d2856b46339d, []int{3}
}

func (m *GetClassReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClassReq.Unmarshal(m, b)
}
func (m *GetClassReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClassReq.Marshal(b, m, deterministic)
}
func (m *GetClassReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClassReq.Merge(m, src)
}
func (m *GetClassReq) XXX_Size() int {
	return xxx_messageInfo_GetClassReq.Size(m)
}
func (m *GetClassReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClassReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetClassReq proto.InternalMessageInfo

func (m *GetClassReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceProvider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceProvider) Reset()         { *m = ServiceProvider{} }
func (m *ServiceProvider) String() string { return proto.CompactTextString(m) }
func (*ServiceProvider) ProtoMessage()    {}
func (*ServiceProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_5954d2856b46339d, []int{4}
}

func (m *ServiceProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceProvider.Unmarshal(m, b)
}
func (m *ServiceProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceProvider.Marshal(b, m, deterministic)
}
func (m *ServiceProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceProvider.Merge(m, src)
}
func (m *ServiceProvider) XXX_Size() int {
	return xxx_messageInfo_ServiceProvider.Size(m)
}
func (m *ServiceProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceProvider proto.InternalMessageInfo

func (m *ServiceProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceProvider) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func init() {
	proto.RegisterEnum("appointy.class.v1.ClassType", ClassType_name, ClassType_value)
	proto.RegisterType((*Class)(nil), "appointy.class.v1.Class")
	proto.RegisterMapType((map[string]*Value)(nil), "appointy.class.v1.Class.MetadataEntry")
	proto.RegisterType((*Value)(nil), "appointy.class.v1.Value")
	proto.RegisterType((*CreateClassReq)(nil), "appointy.class.v1.CreateClassReq")
	proto.RegisterType((*GetClassReq)(nil), "appointy.class.v1.GetClassReq")
	proto.RegisterType((*ServiceProvider)(nil), "appointy.class.v1.ServiceProvider")
}

func init() { proto.RegisterFile("pb/class.proto", fileDescriptor_5954d2856b46339d) }

var fileDescriptor_5954d2856b46339d = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0xdd, 0xfc, 0x38, 0xd7, 0x6d, 0xbe, 0x7c, 0x83, 0x84, 0x8c, 0x45, 0x8b, 0x31, 0x02,
	0x59, 0x2c, 0x1c, 0x1a, 0x84, 0x04, 0xac, 0x68, 0x9b, 0xa8, 0x8d, 0x54, 0x2a, 0x34, 0xfd, 0x11,
	0x62, 0x41, 0x34, 0xb1, 0x6f, 0x53, 0x8b, 0xf8, 0x87, 0x99, 0x49, 0xa4, 0xbc, 0x19, 0x1b, 0x5e,
	0x81, 0x47, 0x60, 0xc1, 0x93, 0x20, 0x8f, 0x9d, 0x90, 0x36, 0x69, 0x57, 0x99, 0x39, 0x73, 0xce,
	0xcd, 0x3d, 0xe7, 0x5e, 0x43, 0x33, 0x1b, 0xb6, 0x83, 0x31, 0x13, 0xc2, 0xcf, 0x78, 0x2a, 0x53,
	0xf2, 0x3f, 0xcb, 0xb2, 0x34, 0x4a, 0xe4, 0xcc, 0x2f, 0xd0, 0xe9, 0x9e, 0xfd, 0x64, 0x94, 0xa6,
	0xa3, 0x31, 0xb6, 0x15, 0x61, 0x38, 0xb9, 0x6a, 0xcb, 0x28, 0x46, 0x21, 0x59, 0x9c, 0x15, 0x1a,
	0x7b, 0xf7, 0x36, 0x21, 0x9c, 0x70, 0x26, 0xa3, 0x34, 0x29, 0xdf, 0x1f, 0x88, 0xe0, 0x1a, 0x63,
	0xd6, 0x2e, 0x7e, 0x0a, 0xd0, 0xfd, 0x55, 0x81, 0xea, 0x61, 0xfe, 0x17, 0xa4, 0x09, 0x7a, 0x14,
	0x5a, 0x9a, 0xa3, 0x79, 0x0d, 0xaa, 0x47, 0x21, 0x21, 0x50, 0x61, 0x1c, 0x99, 0xa5, 0x3b, 0x9a,
	0xa7, 0x53, 0x75, 0x26, 0x36, 0x18, 0x42, 0x72, 0x4c, 0x46, 0xf2, 0xda, 0xda, 0x74, 0x34, 0xaf,
	0x4a, 0x17, 0x77, 0xb2, 0x03, 0x10, 0x89, 0x41, 0x88, 0x63, 0x94, 0x18, 0x5a, 0x15, 0x47, 0xf3,
	0x0c, 0xda, 0x88, 0x44, 0xb7, 0x00, 0xc8, 0x2b, 0xa8, 0xc8, 0x59, 0x86, 0x56, 0xd5, 0xd1, 0xbc,
	0x66, 0xe7, 0xb1, 0xbf, 0x62, 0xd0, 0x57, 0x6d, 0x9c, 0xcf, 0x32, 0xa4, 0x8a, 0x49, 0xba, 0x60,
	0x46, 0x89, 0x90, 0x7c, 0x12, 0xc8, 0x94, 0x0b, 0xab, 0xe6, 0x6c, 0x7a, 0x66, 0xc7, 0x5d, 0x23,
	0x3c, 0x43, 0x3e, 0x8d, 0x02, 0xfc, 0xc4, 0xd3, 0x69, 0x14, 0x22, 0xa7, 0xcb, 0x32, 0xf2, 0x0c,
	0xb6, 0x32, 0xe4, 0x83, 0x1c, 0x62, 0x49, 0x80, 0x56, 0x3d, 0x37, 0x78, 0xbc, 0x41, 0xcd, 0x0c,
	0x79, 0xbf, 0x04, 0x89, 0x0d, 0xf5, 0xf1, 0x24, 0xce, 0xc4, 0x24, 0xb6, 0x8c, 0xdc, 0xd6, 0xf1,
	0x06, 0x9d, 0x03, 0xe4, 0x00, 0x8c, 0x18, 0x25, 0x0b, 0x99, 0x64, 0x56, 0x43, 0xf5, 0xf0, 0xe2,
	0xae, 0xe6, 0xfd, 0x8f, 0x25, 0xb1, 0x97, 0x48, 0x3e, 0xa3, 0x0b, 0x1d, 0x79, 0x08, 0xb5, 0x8c,
	0x71, 0x4c, 0xa4, 0x05, 0x2a, 0xdf, 0xf2, 0x46, 0xde, 0x01, 0x08, 0xc9, 0xb8, 0x1c, 0x84, 0x4c,
	0xa2, 0x65, 0x3a, 0x9a, 0x67, 0x76, 0x6c, 0xbf, 0x98, 0xa3, 0x3f, 0x9f, 0xa3, 0x7f, 0x3e, 0x1f,
	0x34, 0x6d, 0x28, 0x76, 0x97, 0x49, 0x24, 0x6f, 0xc0, 0x98, 0xcf, 0xd7, 0xda, 0x52, 0xc2, 0x47,
	0x2b, 0xc2, 0x6e, 0x49, 0xa0, 0x0b, 0xaa, 0x7d, 0x01, 0xdb, 0x37, 0x9a, 0x24, 0x2d, 0xd8, 0xfc,
	0x86, 0xb3, 0x72, 0xee, 0xf9, 0x91, 0xf8, 0x50, 0x9d, 0xb2, 0xf1, 0x04, 0xd5, 0xe4, 0xcd, 0x8e,
	0xb5, 0xc6, 0xed, 0x65, 0xfe, 0x4e, 0x0b, 0xda, 0x7b, 0xfd, 0xad, 0x76, 0x60, 0x40, 0x2d, 0xb8,
	0x66, 0x7c, 0x84, 0x6e, 0x1b, 0xaa, 0xea, 0x35, 0xdf, 0x9f, 0x84, 0xc5, 0x58, 0x56, 0x56, 0xe7,
	0x1c, 0x1b, 0xe5, 0x98, 0x5e, 0x60, 0xf9, 0xd9, 0xfd, 0x0c, 0xcd, 0x43, 0x8e, 0x4c, 0xa2, 0x8a,
	0x90, 0xe2, 0xf7, 0xa5, 0xb4, 0xb4, 0x1b, 0x69, 0xf9, 0x50, 0x55, 0x1d, 0xdc, 0xd3, 0x58, 0x51,
	0xa3, 0xa0, 0xb9, 0x3b, 0x60, 0x1e, 0xa1, 0x5c, 0x94, 0xbd, 0xb5, 0xe0, 0xee, 0x07, 0xf8, 0xef,
	0xd6, 0xe6, 0xac, 0x7c, 0x03, 0x3b, 0x00, 0x57, 0x11, 0x17, 0x72, 0x90, 0xfc, 0xeb, 0xba, 0xa1,
	0x90, 0x53, 0x16, 0xe3, 0xcb, 0x3d, 0x68, 0x2c, 0x96, 0x96, 0x98, 0x50, 0xef, 0x9f, 0x5e, 0xee,
	0x9f, 0xf4, 0xbb, 0xad, 0x8d, 0xfc, 0x42, 0x7b, 0x47, 0x17, 0x27, 0xfb, 0xb4, 0xa5, 0x11, 0x80,
	0xda, 0x59, 0x8f, 0xf6, 0x7b, 0x67, 0x2d, 0xbd, 0xf3, 0x53, 0x83, 0xba, 0xd2, 0xa0, 0x20, 0x5f,
	0xc1, 0x5c, 0x72, 0x4e, 0x9e, 0xae, 0xf3, 0x73, 0x23, 0x19, 0xfb, 0x4e, 0xcb, 0x2e, 0xf9, 0xf3,
	0xe3, 0xf7, 0xf3, 0x6d, 0x62, 0x06, 0x4b, 0x05, 0x29, 0x18, 0x73, 0xff, 0x64, 0x77, 0x8d, 0x72,
	0x29, 0x9c, 0x7b, 0x2a, 0x6f, 0xe5, 0x95, 0xeb, 0x65, 0xf4, 0x07, 0x95, 0x2f, 0x7a, 0x36, 0x1c,
	0xd6, 0xd4, 0x8a, 0xbd, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x81, 0x5a, 0x16, 0x10, 0xb7, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClassesClient is the client API for Classes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClassesClient interface {
	CreateClass(ctx context.Context, in *CreateClassReq, opts ...grpc.CallOption) (*Class, error)
	GetClass(ctx context.Context, in *GetClassReq, opts ...grpc.CallOption) (*Class, error)
}

type classesClient struct {
	cc *grpc.ClientConn
}

func NewClassesClient(cc *grpc.ClientConn) ClassesClient {
	return &classesClient{cc}
}

func (c *classesClient) CreateClass(ctx context.Context, in *CreateClassReq, opts ...grpc.CallOption) (*Class, error) {
	out := new(Class)
	err := c.cc.Invoke(ctx, "/appointy.class.v1.Classes/CreateClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *classesClient) GetClass(ctx context.Context, in *GetClassReq, opts ...grpc.CallOption) (*Class, error) {
	out := new(Class)
	err := c.cc.Invoke(ctx, "/appointy.class.v1.Classes/GetClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassesServer is the server API for Classes service.
type ClassesServer interface {
	CreateClass(context.Context, *CreateClassReq) (*Class, error)
	GetClass(context.Context, *GetClassReq) (*Class, error)
}

func RegisterClassesServer(s *grpc.Server, srv ClassesServer) {
	s.RegisterService(&_Classes_serviceDesc, srv)
}

func _Classes_CreateClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassesServer).CreateClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.class.v1.Classes/CreateClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassesServer).CreateClass(ctx, req.(*CreateClassReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Classes_GetClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassesServer).GetClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appointy.class.v1.Classes/GetClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassesServer).GetClass(ctx, req.(*GetClassReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Classes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "appointy.class.v1.Classes",
	HandlerType: (*ClassesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClass",
			Handler:    _Classes_CreateClass_Handler,
		},
		{
			MethodName: "GetClass",
			Handler:    _Classes_GetClass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/class.proto",
}
