// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validate/schema.proto

package validate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MethodOptions struct {
	// Types that are valid to be assigned to Type:
	//	*MethodOptions_Query
	//	*MethodOptions_Mutation
	Type                 isMethodOptions_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MethodOptions) Reset()         { *m = MethodOptions{} }
func (m *MethodOptions) String() string { return proto.CompactTextString(m) }
func (*MethodOptions) ProtoMessage()    {}
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_fffe6b622917d52e, []int{0}
}

func (m *MethodOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MethodOptions.Unmarshal(m, b)
}
func (m *MethodOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MethodOptions.Marshal(b, m, deterministic)
}
func (m *MethodOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MethodOptions.Merge(m, src)
}
func (m *MethodOptions) XXX_Size() int {
	return xxx_messageInfo_MethodOptions.Size(m)
}
func (m *MethodOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MethodOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MethodOptions proto.InternalMessageInfo

type isMethodOptions_Type interface {
	isMethodOptions_Type()
}

type MethodOptions_Query struct {
	Query string `protobuf:"bytes,1,opt,name=query,proto3,oneof"`
}

type MethodOptions_Mutation struct {
	Mutation string `protobuf:"bytes,2,opt,name=mutation,proto3,oneof"`
}

func (*MethodOptions_Query) isMethodOptions_Type() {}

func (*MethodOptions_Mutation) isMethodOptions_Type() {}

func (m *MethodOptions) GetType() isMethodOptions_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *MethodOptions) GetQuery() string {
	if x, ok := m.GetType().(*MethodOptions_Query); ok {
		return x.Query
	}
	return ""
}

func (m *MethodOptions) GetMutation() string {
	if x, ok := m.GetType().(*MethodOptions_Mutation); ok {
		return x.Mutation
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MethodOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MethodOptions_Query)(nil),
		(*MethodOptions_Mutation)(nil),
	}
}

var E_Schema = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MethodOptions)(nil),
	Field:         9892748,
	Name:          "graphql.schema",
	Tag:           "bytes,9892748,opt,name=schema",
	Filename:      "validate/schema.proto",
}

func init() {
	proto.RegisterType((*MethodOptions)(nil), "graphql.MethodOptions")
	proto.RegisterExtension(E_Schema)
}

func init() { proto.RegisterFile("validate/schema.proto", fileDescriptor_fffe6b622917d52e) }

var fileDescriptor_fffe6b622917d52e = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4b, 0xcc, 0xc9,
	0x4c, 0x49, 0x2c, 0x49, 0xd5, 0x2f, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x4f, 0x2f, 0x4a, 0x2c, 0xc8, 0x28, 0xcc, 0x91, 0x52, 0x48, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x27, 0x95, 0xa6, 0xe9, 0xa7, 0xa4, 0x16, 0x27, 0x17, 0x65, 0x16,
	0x94, 0xe4, 0x17, 0x41, 0x94, 0x2a, 0xf9, 0x72, 0xf1, 0xfa, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0xf8,
	0x17, 0x94, 0x64, 0xe6, 0xe7, 0x15, 0x0b, 0x89, 0x71, 0xb1, 0x16, 0x96, 0xa6, 0x16, 0x55, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x7a, 0x30, 0x04, 0x41, 0xb8, 0x42, 0x32, 0x5c, 0x1c, 0xb9, 0xa5,
	0x25, 0x89, 0x20, 0x45, 0x12, 0x4c, 0x50, 0x29, 0xb8, 0x88, 0x13, 0x1b, 0x17, 0x4b, 0x49, 0x65,
	0x41, 0xaa, 0x55, 0x20, 0x17, 0x1b, 0xc4, 0x25, 0x42, 0x72, 0x7a, 0x10, 0xbb, 0xf5, 0x60, 0x76,
	0xeb, 0xa1, 0xd8, 0x23, 0xd1, 0xf3, 0xfc, 0x36, 0x8b, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x98, 0x1e,
	0xd4, 0xb5, 0xa8, 0x0a, 0x82, 0xa0, 0x06, 0x39, 0x69, 0x44, 0xa9, 0xa5, 0xe7, 0xeb, 0x25, 0x16,
	0x14, 0xe4, 0x67, 0xe6, 0x95, 0x54, 0xea, 0x25, 0xe7, 0xe7, 0xea, 0xc3, 0x38, 0xfa, 0x59, 0x89,
	0x89, 0x39, 0xfa, 0xb0, 0x30, 0x48, 0x62, 0x03, 0x5b, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xb1, 0x98, 0x4c, 0xbb, 0x16, 0x01, 0x00, 0x00,
}
