// Code generated by protoc-gen-lc, DO NOT EDIT.

package pb

import "context"
import "google.golang.org/grpc"

type localClassesClient struct {
	ClassesServer
}

func NewLocalClassesClient(s ClassesServer) ClassesClient {
	return &localClassesClient{s}
}

func (lc *localClassesClient) CreateClass(ctx context.Context, in *CreateClassReq, opts ...grpc.CallOption) (*Class, error) {
	return lc.ClassesServer.CreateClass(ctx, in)
}

func (lc *localClassesClient) GetClass(ctx context.Context, in *GetClassReq, opts ...grpc.CallOption) (*Class, error) {
	return lc.ClassesServer.GetClass(ctx, in)
}
