// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/pb/class.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClassType int32

const (
	ClassType_INVALID ClassType = 0
	ClassType_REGULAR ClassType = 1
	ClassType_SERIES  ClassType = 2
)

var ClassType_name = map[int32]string{
	0: "INVALID",
	1: "REGULAR",
	2: "SERIES",
}

var ClassType_value = map[string]int32{
	"INVALID": 0,
	"REGULAR": 1,
	"SERIES":  2,
}

func (x ClassType) String() string {
	return proto.EnumName(ClassType_name, int32(x))
}

func (ClassType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{0}
}

type Class struct {
	Id          string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Area        float32            `protobuf:"fixed32,2,opt,name=area,proto3" json:"area,omitempty"`
	Strength    int32              `protobuf:"varint,3,opt,name=strength,proto3" json:"strength,omitempty"`
	IsDeleted   bool               `protobuf:"varint,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Type        ClassType          `protobuf:"varint,5,opt,name=type,proto3,enum=appointy.class.v1.ClassType" json:"type,omitempty"`
	Instructors []*ServiceProvider `protobuf:"bytes,6,rep,name=instructors,proto3" json:"instructors,omitempty"`
	// Types that are valid to be assigned to Charge:
	//	*Class_PerInstance
	//	*Class_Lumpsum
	Charge               isClass_Charge       `protobuf_oneof:"charge"`
	Metadata             map[string]string    `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Parent               string               `protobuf:"bytes,10,opt,name=parent,proto3" json:"parent,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	Duration             *duration.Duration   `protobuf:"bytes,12,opt,name=duration,proto3" json:"duration,omitempty"`
	Empty                *empty.Empty         `protobuf:"bytes,13,opt,name=empty,proto3" json:"empty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Class) Reset()         { *m = Class{} }
func (m *Class) String() string { return proto.CompactTextString(m) }
func (*Class) ProtoMessage()    {}
func (*Class) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{0}
}

func (m *Class) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Class.Unmarshal(m, b)
}
func (m *Class) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Class.Marshal(b, m, deterministic)
}
func (m *Class) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Class.Merge(m, src)
}
func (m *Class) XXX_Size() int {
	return xxx_messageInfo_Class.Size(m)
}
func (m *Class) XXX_DiscardUnknown() {
	xxx_messageInfo_Class.DiscardUnknown(m)
}

var xxx_messageInfo_Class proto.InternalMessageInfo

func (m *Class) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Class) GetArea() float32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Class) GetStrength() int32 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *Class) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Class) GetType() ClassType {
	if m != nil {
		return m.Type
	}
	return ClassType_INVALID
}

func (m *Class) GetInstructors() []*ServiceProvider {
	if m != nil {
		return m.Instructors
	}
	return nil
}

type isClass_Charge interface {
	isClass_Charge()
}

type Class_PerInstance struct {
	PerInstance string `protobuf:"bytes,7,opt,name=per_instance,json=perInstance,proto3,oneof"`
}

type Class_Lumpsum struct {
	Lumpsum int32 `protobuf:"varint,8,opt,name=Lumpsum,proto3,oneof"`
}

func (*Class_PerInstance) isClass_Charge() {}

func (*Class_Lumpsum) isClass_Charge() {}

func (m *Class) GetCharge() isClass_Charge {
	if m != nil {
		return m.Charge
	}
	return nil
}

func (m *Class) GetPerInstance() string {
	if x, ok := m.GetCharge().(*Class_PerInstance); ok {
		return x.PerInstance
	}
	return ""
}

func (m *Class) GetLumpsum() int32 {
	if x, ok := m.GetCharge().(*Class_Lumpsum); ok {
		return x.Lumpsum
	}
	return 0
}

func (m *Class) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Class) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Class) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Class) GetDuration() *duration.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *Class) GetEmpty() *empty.Empty {
	if m != nil {
		return m.Empty
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Class) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Class_PerInstance)(nil),
		(*Class_Lumpsum)(nil),
	}
}

type CreateClassReq struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Class                *Class   `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClassReq) Reset()         { *m = CreateClassReq{} }
func (m *CreateClassReq) String() string { return proto.CompactTextString(m) }
func (*CreateClassReq) ProtoMessage()    {}
func (*CreateClassReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{1}
}

func (m *CreateClassReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClassReq.Unmarshal(m, b)
}
func (m *CreateClassReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClassReq.Marshal(b, m, deterministic)
}
func (m *CreateClassReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClassReq.Merge(m, src)
}
func (m *CreateClassReq) XXX_Size() int {
	return xxx_messageInfo_CreateClassReq.Size(m)
}
func (m *CreateClassReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClassReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClassReq proto.InternalMessageInfo

func (m *CreateClassReq) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateClassReq) GetClass() *Class {
	if m != nil {
		return m.Class
	}
	return nil
}

type GetClassReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClassReq) Reset()         { *m = GetClassReq{} }
func (m *GetClassReq) String() string { return proto.CompactTextString(m) }
func (*GetClassReq) ProtoMessage()    {}
func (*GetClassReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{2}
}

func (m *GetClassReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClassReq.Unmarshal(m, b)
}
func (m *GetClassReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClassReq.Marshal(b, m, deterministic)
}
func (m *GetClassReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClassReq.Merge(m, src)
}
func (m *GetClassReq) XXX_Size() int {
	return xxx_messageInfo_GetClassReq.Size(m)
}
func (m *GetClassReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClassReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetClassReq proto.InternalMessageInfo

func (m *GetClassReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceProvider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceProvider) Reset()         { *m = ServiceProvider{} }
func (m *ServiceProvider) String() string { return proto.CompactTextString(m) }
func (*ServiceProvider) ProtoMessage()    {}
func (*ServiceProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{3}
}

func (m *ServiceProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceProvider.Unmarshal(m, b)
}
func (m *ServiceProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceProvider.Marshal(b, m, deterministic)
}
func (m *ServiceProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceProvider.Merge(m, src)
}
func (m *ServiceProvider) XXX_Size() int {
	return xxx_messageInfo_ServiceProvider.Size(m)
}
func (m *ServiceProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceProvider.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceProvider proto.InternalMessageInfo

func (m *ServiceProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ServiceProvider) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

type PerInstance struct {
	Cost                 *Price   `protobuf:"bytes,2,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerInstance) Reset()         { *m = PerInstance{} }
func (m *PerInstance) String() string { return proto.CompactTextString(m) }
func (*PerInstance) ProtoMessage()    {}
func (*PerInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{4}
}

func (m *PerInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerInstance.Unmarshal(m, b)
}
func (m *PerInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerInstance.Marshal(b, m, deterministic)
}
func (m *PerInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerInstance.Merge(m, src)
}
func (m *PerInstance) XXX_Size() int {
	return xxx_messageInfo_PerInstance.Size(m)
}
func (m *PerInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_PerInstance.DiscardUnknown(m)
}

var xxx_messageInfo_PerInstance proto.InternalMessageInfo

func (m *PerInstance) GetCost() *Price {
	if m != nil {
		return m.Cost
	}
	return nil
}

type Lumpsum struct {
	Cost                 *Price   `protobuf:"bytes,1,opt,name=cost,proto3" json:"cost,omitempty"`
	NumberOfSessions     int32    `protobuf:"varint,2,opt,name=number_of_sessions,json=numberOfSessions,proto3" json:"number_of_sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lumpsum) Reset()         { *m = Lumpsum{} }
func (m *Lumpsum) String() string { return proto.CompactTextString(m) }
func (*Lumpsum) ProtoMessage()    {}
func (*Lumpsum) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{5}
}

func (m *Lumpsum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lumpsum.Unmarshal(m, b)
}
func (m *Lumpsum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lumpsum.Marshal(b, m, deterministic)
}
func (m *Lumpsum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lumpsum.Merge(m, src)
}
func (m *Lumpsum) XXX_Size() int {
	return xxx_messageInfo_Lumpsum.Size(m)
}
func (m *Lumpsum) XXX_DiscardUnknown() {
	xxx_messageInfo_Lumpsum.DiscardUnknown(m)
}

var xxx_messageInfo_Lumpsum proto.InternalMessageInfo

func (m *Lumpsum) GetCost() *Price {
	if m != nil {
		return m.Cost
	}
	return nil
}

func (m *Lumpsum) GetNumberOfSessions() int32 {
	if m != nil {
		return m.NumberOfSessions
	}
	return 0
}

type Price struct {
	Amount               int32    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cf53c799ece0d8b, []int{6}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterEnum("appointy.class.v1.ClassType", ClassType_name, ClassType_value)
	proto.RegisterType((*Class)(nil), "appointy.class.v1.Class")
	proto.RegisterMapType((map[string]string)(nil), "appointy.class.v1.Class.MetadataEntry")
	proto.RegisterType((*CreateClassReq)(nil), "appointy.class.v1.CreateClassReq")
	proto.RegisterType((*GetClassReq)(nil), "appointy.class.v1.GetClassReq")
	proto.RegisterType((*ServiceProvider)(nil), "appointy.class.v1.ServiceProvider")
	proto.RegisterType((*PerInstance)(nil), "appointy.class.v1.PerInstance")
	proto.RegisterType((*Lumpsum)(nil), "appointy.class.v1.Lumpsum")
	proto.RegisterType((*Price)(nil), "appointy.class.v1.Price")
}

func init() { proto.RegisterFile("example/pb/class.proto", fileDescriptor_5cf53c799ece0d8b) }

var fileDescriptor_5cf53c799ece0d8b = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x61, 0x6f, 0xd3, 0x4a,
	0x10, 0xac, 0xd3, 0x38, 0x4d, 0xd6, 0x6d, 0x5f, 0xde, 0xe9, 0xa9, 0xba, 0x17, 0x28, 0x44, 0x46,
	0x42, 0x11, 0xaa, 0x5c, 0x1a, 0x84, 0x04, 0xf4, 0x0b, 0x6d, 0x13, 0xb5, 0x91, 0x4a, 0xa9, 0x2e,
	0x05, 0x21, 0xbe, 0x44, 0x17, 0x7b, 0x93, 0x5a, 0xc4, 0xf6, 0x71, 0x77, 0x8e, 0xc8, 0xdf, 0xe5,
	0x97, 0x20, 0x9f, 0x1d, 0xab, 0x4d, 0x28, 0xe2, 0x9b, 0x77, 0x76, 0xc6, 0xde, 0x9d, 0x1d, 0xc3,
	0x1e, 0xfe, 0xe0, 0x91, 0x98, 0xe1, 0xa1, 0x18, 0x1f, 0xfa, 0x33, 0xae, 0x94, 0x27, 0x64, 0xa2,
	0x13, 0xf2, 0x2f, 0x17, 0x22, 0x09, 0x63, 0xbd, 0xf0, 0x72, 0x74, 0x7e, 0xd4, 0x7a, 0x3a, 0x4d,
	0x92, 0x69, 0xc6, 0xcc, 0x08, 0xe3, 0x74, 0x72, 0xa8, 0xc3, 0x08, 0x95, 0xe6, 0x91, 0xc8, 0x35,
	0xad, 0x27, 0xab, 0x84, 0x20, 0x95, 0x5c, 0x87, 0x49, 0x5c, 0xf4, 0x1f, 0xad, 0xf6, 0x31, 0x12,
	0x7a, 0x91, 0x37, 0xdd, 0x9f, 0x55, 0xb0, 0xcf, 0xb2, 0x4f, 0x91, 0x5d, 0xa8, 0x84, 0x01, 0xb5,
	0xda, 0x56, 0xa7, 0xc1, 0x2a, 0x61, 0x40, 0x08, 0x54, 0xb9, 0x44, 0x4e, 0x2b, 0x6d, 0xab, 0x53,
	0x61, 0xe6, 0x99, 0xb4, 0xa0, 0xae, 0xb4, 0xc4, 0x78, 0xaa, 0x6f, 0xe9, 0x66, 0xdb, 0xea, 0xd8,
	0xac, 0xac, 0xc9, 0x3e, 0x40, 0xa8, 0x46, 0x01, 0xce, 0x50, 0x63, 0x40, 0xab, 0x6d, 0xab, 0x53,
	0x67, 0x8d, 0x50, 0xf5, 0x72, 0x80, 0xbc, 0x84, 0xaa, 0x5e, 0x08, 0xa4, 0x76, 0xdb, 0xea, 0xec,
	0x76, 0x1f, 0x7b, 0x6b, 0x8b, 0x7a, 0x66, 0x8c, 0x9b, 0x85, 0x40, 0x66, 0x98, 0xa4, 0x07, 0x4e,
	0x18, 0x2b, 0x2d, 0x53, 0x5f, 0x27, 0x52, 0xd1, 0x5a, 0x7b, 0xb3, 0xe3, 0x74, 0xdd, 0xdf, 0x08,
	0x87, 0x28, 0xe7, 0xa1, 0x8f, 0xd7, 0x32, 0x99, 0x87, 0x01, 0x4a, 0x76, 0x57, 0x46, 0x9e, 0xc1,
	0xb6, 0x40, 0x39, 0xca, 0x20, 0x1e, 0xfb, 0x48, 0xb7, 0xb2, 0x05, 0x2f, 0x36, 0x98, 0x23, 0x50,
	0x0e, 0x0a, 0x90, 0xb4, 0x60, 0xeb, 0x32, 0x8d, 0x84, 0x4a, 0x23, 0x5a, 0xcf, 0xd6, 0xba, 0xd8,
	0x60, 0x4b, 0x80, 0x9c, 0x42, 0x3d, 0x42, 0xcd, 0x03, 0xae, 0x39, 0x6d, 0x98, 0x19, 0x9e, 0x3f,
	0x34, 0xbc, 0xf7, 0xa1, 0x20, 0xf6, 0x63, 0x2d, 0x17, 0xac, 0xd4, 0x91, 0x3d, 0xa8, 0x09, 0x2e,
	0x31, 0xd6, 0x14, 0x8c, 0xbf, 0x45, 0x45, 0xde, 0x02, 0x28, 0xcd, 0xa5, 0x1e, 0x05, 0x5c, 0x23,
	0x75, 0xda, 0x56, 0xc7, 0xe9, 0xb6, 0xbc, 0xfc, 0x5e, 0xde, 0xf2, 0x5e, 0xde, 0xcd, 0xf2, 0xe0,
	0xac, 0x61, 0xd8, 0x3d, 0xae, 0x91, 0xbc, 0x86, 0xfa, 0xf2, 0xce, 0x74, 0xdb, 0x08, 0xff, 0x5f,
	0x13, 0xf6, 0x0a, 0x02, 0x2b, 0xa9, 0xe4, 0x00, 0x6c, 0x73, 0x7e, 0xba, 0x63, 0x34, 0x7b, 0x6b,
	0x9a, 0x7e, 0xd6, 0x65, 0x39, 0xa9, 0x75, 0x0c, 0x3b, 0xf7, 0x56, 0x22, 0x4d, 0xd8, 0xfc, 0x86,
	0x8b, 0x22, 0x25, 0xd9, 0x23, 0xf9, 0x0f, 0xec, 0x39, 0x9f, 0xa5, 0x68, 0x72, 0xd2, 0x60, 0x79,
	0xf1, 0xae, 0xf2, 0xc6, 0x3a, 0xad, 0x43, 0xcd, 0xbf, 0xe5, 0x72, 0x8a, 0xee, 0x17, 0xd8, 0x3d,
	0x93, 0xc8, 0x35, 0x1a, 0x97, 0x18, 0x7e, 0xbf, 0x63, 0x88, 0x75, 0xcf, 0x10, 0x0f, 0x6c, 0x63,
	0xa9, 0x79, 0x9b, 0xd3, 0xa5, 0x0f, 0x39, 0xcd, 0x72, 0x9a, 0xbb, 0x0f, 0xce, 0x39, 0xea, 0xf2,
	0xb5, 0x2b, 0x19, 0x76, 0xdf, 0xc3, 0x3f, 0x2b, 0xe1, 0x58, 0x8b, 0xf9, 0x3e, 0xc0, 0x24, 0x94,
	0x4a, 0x8f, 0x62, 0x1e, 0x2d, 0x97, 0x68, 0x18, 0xe4, 0x8a, 0x47, 0xe8, 0x1e, 0x83, 0x73, 0x7d,
	0x27, 0x28, 0x07, 0x50, 0xf5, 0x13, 0xa5, 0xff, 0x30, 0xde, 0xb5, 0x0c, 0x7d, 0x64, 0x86, 0xe5,
	0x62, 0x19, 0xab, 0x52, 0x68, 0xfd, 0x8d, 0x90, 0x1c, 0x00, 0x89, 0xd3, 0x68, 0x8c, 0x72, 0x94,
	0x4c, 0x46, 0x0a, 0x95, 0x0a, 0x93, 0x38, 0xf7, 0xc4, 0x66, 0xcd, 0xbc, 0xf3, 0x71, 0x32, 0x2c,
	0x70, 0xf7, 0x18, 0x6c, 0x23, 0xce, 0x5c, 0xe5, 0x51, 0x92, 0x16, 0xae, 0xda, 0xac, 0xa8, 0xb2,
	0xdf, 0xd6, 0x4f, 0xa5, 0xc4, 0xd8, 0x5f, 0x14, 0x1b, 0x96, 0xf5, 0x8b, 0x23, 0x68, 0x94, 0x3f,
	0x1e, 0x71, 0x60, 0x6b, 0x70, 0xf5, 0xf9, 0xe4, 0x72, 0xd0, 0x6b, 0x6e, 0x64, 0x05, 0xeb, 0x9f,
	0x7f, 0xba, 0x3c, 0x61, 0x4d, 0x8b, 0x00, 0xd4, 0x86, 0x7d, 0x36, 0xe8, 0x0f, 0x9b, 0x95, 0xd3,
	0xea, 0xd7, 0x8a, 0x18, 0x8f, 0x6b, 0x26, 0x32, 0xaf, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf1,
	0xfa, 0x35, 0x54, 0xcb, 0x04, 0x00, 0x00,
}
